/**
 * Les portraits audio des six Reflets (idée de Sandro, 11 septembre 2026) :
 * une définition claire de chaque parfum, dans la voix de Luma, écrite une
 * fois, générée une fois (scripts/luma-voice-portraits.mjs), servie en fichier
 * statique — zéro crédit à l'écoute. Fiche produit et cartes de Luma y renvoient.
 *
 * Structure (registre validé par Sandro le 11 septembre 2026, v3 « parlé ») :
 * une accroche qui s'adresse au visiteur ; une scène qu'on voit (« imaginez… ») ;
 * la pyramide racontée en phrases courtes ; LE MOT DU PARFUMEUR — l'intention,
 * l'inspiration, cité sans le nommer (REFLET_BRIEFS.perfumer) ; la filiation
 * (« notre réinterprétation de… ») ; le caractère en trois mots, dit plus bas.
 * Pas de question : c'est un portrait. Environ une minute. Les indications entre crochets sont
 * pour la voix (v3) et retirées du texte affiché. Mêmes interdits que Luma.
 *
 * Arabe : voix d'homme (Jeddawi), donc « la voix de la Maison » et non Luma ;
 * arabe standard, courtoisie du Golfe, noms des parfums et des références en
 * caractères latins. Une image adaptée quand il le faut (un kob dafi' plutôt
 * qu'« un verre »). À faire écouter à un natif avant la production.
 */

import type { Locale } from "../../i18n";

export const PORTRAITS: Partial<Record<Locale, Record<string, string>>> = {
  fr: {
    "bois-alert":
      "[warmly] Bois Alert… c'est celui que je vous tends quand vous ne savez pas par où commencer. [inhales] Imaginez une chemise blanche, un matin où tout est net. Vous le mettez sans réfléchir — et on le remarque sur vous toute la journée. [exhales] Ça commence par du poivre noir et du safran, avec du tempérament ; la bergamote de Calabre vient alléger tout ça. Puis le cœur : le jasmin sambac, qui irradie sur l'ambre gris et une pointe de caramel. Et en fond, vétiver, patchouli, cèdre — le bois, franc, vibrant. [warmly] Le parfumeur voulait donner une nouvelle dimension aux bois, jouer avec leur force et leur vibration naturelle. Le safran et le jasmin apportent le contraste et l'éclat ; les facettes moussues et ambrées, la profondeur et le sillage. C'est notre réinterprétation de Bois Impérial, enrichie des facettes safran et jasmin de Baccarat Rouge 540. [softly] Magnétique, distinct, rayonnant. Le feu que les deux rives reconnaissent.",
    "new-oud":
      "[warmly] New Oud… c'est l'oud pour ceux qui l'aiment, et qui ne veulent pas qu'il pèse. [inhales] Imaginez la nuit qui tombe sur une terrasse de Riyad, l'air encore chaud. Quelque chose de précieux, porté près de soi. [exhales] Ça s'ouvre sur le fruit de la passion et la mandarine, vifs, avec le safran. Puis le cœur : la rose de Taïf et le muguet, qui éclairent l'ambre. Et en fond, l'oud s'installe — profond — adouci par un bois de santal crémeux et le musc blanc. [warmly] Le parfumeur voulait garder toute la richesse, toute l'opulence de l'oud, mais lui donner une expression franchement moderne : son caractère boisé profond, mis en tension avec des fruits vibrants, des muscs crémeux, des fleurs lumineuses. C'est notre réinterprétation d'Oud Maracuja, avec un santal poudré et un floral blanc lumineux. [softly] Intense, profond, opulent. L'oud qui respire.",
    "melting-mango":
      "[upbeat] Melting Mango… si vous portez Baccarat Rouge, c'est celui-là que je vous fais sentir en premier. [inhales] Imaginez une fin d'après-midi d'été. Une mangue coupée au couteau, le jus qui coule sur les doigts — et derrière, cette chaleur ambrée qu'on reconnaît entre mille. [exhales] Ça éclate sur la mangue et l'orange, avec le safran. Puis le cœur : la praline, le noyau d'abricot, le jasmin absolu — la gourmandise s'installe. Et en fond, la mousse de chêne, le patchouli, le vétiver d'Haïti tiennent tout ça, profonds, diffusants. [warmly] Le parfumeur a voulu explorer la tension entre deux sensations opposées : la signature ambrée-boisée, audacieuse, addictive — et l'éclat presque électrique de la mangue. Un fruit travaillé comme lumineux et addictif à la fois, en contraste avec des bois profonds. C'est notre réinterprétation de Baccarat Rouge 540, avec cette surdose de mangue que l'original n'a pas. [softly] Audacieux, moderne, captivant.",
    "ultra-cuir":
      "[warmly] Ultra Cuir… c'est celui du soir. [inhales] Imaginez une veste de cuir qu'on garde sur les épaules quand la nuit tombe, une lumière basse, quelqu'un qui se rapproche. [exhales] Ça s'ouvre sur la framboise, juteuse, avec la bergamote de Calabre et une baie rouge — une lumière posée sur le cuir. Puis le cœur : l'encens, un trio de safrans qui donne la texture, et l'iris, poudré, qui adoucit. Et en fond, le cèdre, le cuir, le patchouli s'installent pour la nuit. [warmly] Le parfumeur voulait redessiner la signature du cuir fruité avec des matières plus précieuses, plus singulières : le safran et l'iris, deux des ingrédients les plus nobles de la parfumerie, pour la texture et le contraste. C'est notre réinterprétation de Tuscan Leather, plus lumineuse au départ, plus texturée au cœur. [softly] Sombre, texturé, mystérieux.",
    "minuit-bourbon":
      "[warmly] Minuit Bourbon… c'est la gourmandise de la nuit. [inhales] Imaginez une soirée d'hiver, un plaid, une tasse qu'on tient longtemps entre les mains. [exhales] La cardamome et la cannelle de Ceylan ouvrent avec de la chaleur. Puis le cœur : la fleur d'oranger et l'amande adoucissent tout. Et en fond, la fève tonka et la vanille Bourbon s'installent, tenues par un accord cuir qui empêche la gourmandise de sombrer dans le trop sucré. [warmly] Le parfumeur cherchait l'addiction, mais dans une expression plus précieuse : des baumes riches, la vanille, la fève tonka — et en face, la fleur d'oranger et la lavande, pour l'éclat et une tension aromatique. C'est notre réinterprétation d'Althaïr, enrichie de ce cuir qui lui donne du caractère. [softly] Chaud, sophistiqué, addictif.",
    "fifth-season":
      "[upbeat] Fifth Season… c'est celui du jour, le plus frais de la collection. [inhales] Imaginez un matin de printemps qui ressemble déjà à l'été. Une fenêtre ouverte, du linge propre, de la lumière partout. [exhales] Ça s'ouvre sur la mandarine, l'orange, les fruits exotiques — vibrants — avec une fraîcheur de fougère. Puis le cœur : le jasmin sambac et le muguet, posés sur un caramel léger. Et en fond, la vanille Bourbon, la fève tonka, le musc blanc arrondissent tout, crémeux, propres. [warmly] Le parfumeur voulait un parfum à facettes, construit sur des contrastes mais facile à porter : entre fraîcheur, addiction et sensualité, avec une diffusion qui s'épanouit et révèle de nouvelles facettes au fil de la journée. C'est notre réinterprétation d'Erba Pura, adoucie d'une touche lactée. [softly] Vibrant, versatile, raffiné.",
  },
  en: {
    "bois-alert":
      "[warmly] Bois Alert… it's the one I hand you when you don't know where to start. [inhales] Picture a crisp white shirt, a morning when everything feels sharp. You put it on without thinking — and people notice it on you all day. [exhales] It starts with black pepper and saffron, full of character; Calabrian bergamot lightens it all. Then the heart: sambac jasmine, radiating over ambergris and a touch of caramel. And in the base, vetiver, patchouli, cedar — the wood, bold and vibrant. [warmly] The perfumer wanted to give woods a new dimension, to play with their strength and natural vibrancy. Saffron and jasmine bring contrast and radiance; the mossy and ambery facets bring depth and trail. It's our reinterpretation of Bois Impérial, enriched with the saffron and jasmine facets of Baccarat Rouge 540. [softly] Magnetic, distinctive, radiant. The fire both shores recognise.",
    "new-oud":
      "[warmly] New Oud… it's oud for those who love it, and don't want it to weigh on them. [inhales] Picture night falling over a terrace in Riyadh, the air still warm. Something precious, worn close to the skin. [exhales] It opens on passion fruit and mandarin, vivid, with saffron. Then the heart: Taif rose and lily of the valley, lighting up the amber. And in the base, oud settles in — deep — softened by creamy sandalwood and white musk. [warmly] The perfumer wanted to keep all the richness, all the opulence of oud, and give it a distinctly modern expression: its deep woody character, set against vibrant fruits, creamy musks and luminous florals. It's our reinterpretation of Oud Maracuja, with a powdery sandalwood and a luminous white floral. [softly] Intense, deep, opulent. Oud that breathes.",
    "melting-mango":
      "[upbeat] Melting Mango… if you wear Baccarat Rouge, this is the one I'll have you smell first. [inhales] Picture a late summer afternoon. A mango cut with a knife, the juice running down your fingers — and behind it, that amber warmth you would recognise anywhere. [exhales] It bursts open on mango and orange, with saffron. Then the heart: praline, apricot kernel, jasmine absolute — the gourmand side settles in. And in the base, oakmoss, patchouli and Haitian vetiver hold it all, deep and diffusive. [warmly] The perfumer wanted to explore the tension between two opposite sensations: the bold, addictive ambery-woody signature — and the almost electric brightness of mango. A fruit worked as both luminous and addictive, in contrast with deep woods. It's our reinterpretation of Baccarat Rouge 540, with an overdose of mango the original never had. [softly] Bold, modern, captivating.",
    "ultra-cuir":
      "[warmly] Ultra Cuir… it's the one for the evening. [inhales] Picture a leather jacket kept on your shoulders as night falls, a low light, someone drawing closer. [exhales] It opens on raspberry, juicy, with Calabrian bergamot and a red berry — a light laid over the leather. Then the heart: incense, a trio of saffrons that bring the texture, and iris, powdery, that softens it. And in the base, cedar, leather and patchouli settle in for the night. [warmly] The perfumer wanted to redraw the fruity leather signature with more precious, more distinctive materials: saffron and iris, two of perfumery's most noble ingredients, for texture and contrast. It's our reinterpretation of Tuscan Leather, brighter at the start, more textured at the heart. [softly] Dark, textured, mysterious.",
    "minuit-bourbon":
      "[warmly] Minuit Bourbon… it's the gourmand of the night. [inhales] Picture a winter evening, a blanket, a cup held for a long while between your hands. [exhales] Cardamom and Ceylon cinnamon open with warmth. Then the heart: orange blossom and almond soften everything. And in the base, tonka bean and Bourbon vanilla settle in, held by a leather accord that keeps the sweetness from sinking into sugar. [warmly] The perfumer was after addiction, but in a more precious expression: rich balms, vanilla, tonka bean — and against them, orange blossom and lavender, for brightness and aromatic tension. It's our reinterpretation of Althaïr, enriched with the leather that gives it character. [softly] Warm, sophisticated, addictive.",
    "fifth-season":
      "[upbeat] Fifth Season… it's the one for daytime, the freshest of the collection. [inhales] Picture a spring morning that already feels like summer. An open window, clean linen, light everywhere. [exhales] It opens on mandarin, orange, exotic fruits — vibrant — with a fougère freshness. Then the heart: sambac jasmine and lily of the valley, resting on a light caramel. And in the base, Bourbon vanilla, tonka bean and white musk round everything off, creamy and clean. [warmly] The perfumer wanted a multi-faceted fragrance, built on contrasts yet effortless to wear: moving between freshness, addiction and sensuality, with a blooming diffusion that reveals new facets as the day goes on. It's our reinterpretation of Erba Pura, softened with a milky touch. [softly] Vibrant, versatile, refined.",
  },
  ar: {
    "bois-alert":
      "[warmly] Bois Alert… هو ما نقدّمه لكم حين لا تعرفون من أين تبدؤون. [inhales] تخيّلوا قميصًا أبيض بلا تجعيدة، وصباحًا كلُّ شيءٍ فيه واضح. تضعونه دون تفكير — ويلاحظه الآخرون عليكم طوال اليوم. [exhales] يبدأ بالفلفل الأسود والزعفران، بطبعٍ قوي؛ وتأتي برغموت كالابريا لتخفّف كلَّ ذلك. ثم القلب: ياسمين سامباك، يشعّ فوق العنبر الرمادي ولمسةٍ من الكراميل. وفي القاعدة، الفيتيفر والباتشولي وخشب الأرز — الخشب، صريحًا نابضًا. [warmly] أراد العطّار أن يمنح الأخشاب بُعدًا جديدًا، وأن يلعب بقوّتها ونبضها الطبيعي. الزعفران والياسمين يمنحان التباين والإشعاع؛ والأوجه الطحلبية والعنبرية تمنح العمق والأثر. هي إعادة تأويلنا لـ Bois Impérial، مُغناةً بأوجه الزعفران والياسمين من Baccarat Rouge 540. [softly] جذّاب، مميّز، مشعّ. النارُ التي تعرفها الضفّتان.",
    "new-oud":
      "[warmly] New Oud… هو العود لمن يحبّه، ولا يريد أن يثقل عليه. [inhales] تخيّلوا ليلًا يهبط على شرفةٍ في الرياض، والهواء ما زال دافئًا. شيءٌ ثمين، يُحمَل قريبًا من القلب. [exhales] يفتتح بفاكهة الباشن واليوسفي، بحيويةٍ، مع الزعفران. ثم القلب: ورد الطائف وزنبق الوادي، يُنيران العنبر. وفي القاعدة يستقرّ العود — عميقًا — يُليّنه خشب صندلٍ كريمي والمسك الأبيض. [warmly] أراد العطّار أن يحفظ كلَّ غنى العود وفخامته، وأن يمنحه تعبيرًا حديثًا بوضوح: طابعه الخشبي العميق، في مواجهة فواكهٍ نابضة ومسكٍ كريمي وزهورٍ مضيئة. هي إعادة تأويلنا لـ Oud Maracuja، مع صندلٍ بودري وزهورٍ بيضاء مضيئة. [softly] كثيف، عميق، فخم. عودٌ يتنفّس.",
    "melting-mango":
      "[upbeat] Melting Mango… إن كنتم تضعون Baccarat Rouge، فهذا ما نجعلكم تشمّونه أوّلًا. [inhales] تخيّلوا عصرَ يومٍ صيفي. مانجو تُقطَع بالسكين، وعصيرٌ يسيل على الأصابع — وخلف ذلك، دفءٌ عنبري تعرفونه بين ألف. [exhales] ينفجر بالمانجو والبرتقال، مع الزعفران. ثم القلب: البرالين ونواة المشمش وخلاصة الياسمين — تستقرّ الحلاوة. وفي القاعدة، طحلب البلوط والباتشولي وفيتيفر هايتي يحملون كلَّ ذلك، عميقًا ومنتشرًا. [warmly] أراد العطّار أن يستكشف التوتّر بين إحساسَين متضادَّين: التوقيع العنبري الخشبي، الجريء الآسر — وسطوع المانجو الذي يكاد يكون كهربائيًا. فاكهةٌ عُولجت لتكون مضيئةً وآسرة معًا، في مقابل أخشابٍ عميقة. هي إعادة تأويلنا لـ Baccarat Rouge 540، مع جرعةٍ مضاعفة من المانجو لم تكن في الأصل. [softly] جريء، حديث، آسر.",
    "ultra-cuir":
      "[warmly] Ultra Cuir… هو عطر المساء. [inhales] تخيّلوا سترةً من الجلد تبقى على الكتفين حين يهبط الليل، وضوءًا خافتًا، وأحدًا يقترب. [exhales] يفتتح بتوت العليق، عصيرًا، مع برغموت كالابريا والتوت الأحمر — ضوءٌ يستقرّ على الجلد. ثم القلب: البخور، وثلاثةُ أنواعٍ من الزعفران تمنح الملمس، والسوسن البودري يُليّن. وفي القاعدة، خشب الأرز والجلد والباتشولي يستقرّون لليل. [warmly] أراد العطّار أن يعيد رسم توقيع الجلد الفاكهي بموادٍّ أنفس وأكثر تفرّدًا: الزعفران والسوسن، وهما من أنبل مكوّنات صناعة العطور، للملمس والتباين. هي إعادة تأويلنا لـ Tuscan Leather، أكثر إضاءةً في البداية، وأكثر ملمسًا في القلب. [softly] داكن، ذو ملمس، غامض.",
    "minuit-bourbon":
      "[warmly] Minuit Bourbon… هو حلاوة الليل. [inhales] تخيّلوا مساءَ شتاءٍ، وشالًا على الكتفين، وكوبًا دافئًا يُمسَك طويلًا بين اليدين. [exhales] يفتتح الهيل وقرفة سيلان بدفء. ثم القلب: زهر البرتقال واللوز يُليّنان كلَّ شيء. وفي القاعدة تستقرّ حبة التونكا وفانيليا بوربون، يشدّهما اتّفاقُ جلدٍ يمنع الحلاوة من الغرق في السكر. [warmly] كان العطّار يبحث عن الإدمان، لكن بتعبيرٍ أنفس: بلسماتٌ غنية، والفانيليا، وحبة التونكا — وفي مقابلها، زهر البرتقال واللافندر، للإشعاع ولتوتّرٍ عطري. هي إعادة تأويلنا لـ Althaïr، مُغناةً بهذا الجلد الذي يمنحها شخصيّة. [softly] دافئ، راقٍ، آسر.",
    "fifth-season":
      "[upbeat] Fifth Season… هو عطر النهار، الأنعش في المجموعة. [inhales] تخيّلوا صباحَ ربيعٍ يشبه الصيف من الآن. نافذةٌ مفتوحة، وأقمشةٌ نظيفة، وضوءٌ في كلّ مكان. [exhales] يفتتح باليوسفي والبرتقال والفواكه الاستوائية — نابضةً — مع نضارةٍ فوجيرية. ثم القلب: ياسمين سامباك وزنبق الوادي، على كراميلٍ خفيف. وفي القاعدة، فانيليا بوربون وحبة التونكا والمسك الأبيض تُدوّر كلَّ شيء، كريميةً ونقيّة. [warmly] أراد العطّار عطرًا متعدّد الأوجه، مبنيًّا على التباينات لكن سهلَ الارتداء: يتحرّك بين النضارة والإدمان والحسّية، بانتشارٍ يتفتّح ويكشف أوجهًا جديدة على مدار اليوم. هي إعادة تأويلنا لـ Erba Pura، مُليَّنةً بلمسةٍ حليبية. [softly] نابض، متعدّد الأوجه، راقٍ.",
  },
};

/** Le fichier statique du portrait, s'il existe pour cette langue. */
export function portraitAudioPath(locale: Locale, handle: string): string | null {
  return PORTRAITS[locale]?.[handle] ? `/luma/voice/${locale}/parfums/${handle}.mp3` : null;
}

/** Le texte du portrait sans ses indications de voix — pour l'afficher ou le lire à l'écran. */
export function portraitText(locale: Locale, handle: string): string | null {
  const script = PORTRAITS[locale]?.[handle];
  return script ? script.replace(/\[[^\]]{1,40}\]/g, " ").replace(/\s{2,}/g, " ").trim() : null;
}
